# บังคับว่าถ้าใครเข้าพอร์ต 80 (HTTP ธรรมดา) ให้เด้งไป HTTPS อัตโนมัติ
server {
    listen 80;
    server_name localhost;
    return 301 https://localhost:3443$request_uri;
}

# เปิดใช้งาน HTTPS บนพอร์ต 443
server {
    listen 443 ssl;
    server_name localhost;

    # ชี้เป้าไปที่ใบเซอร์ที่เราสร้างไว้
    ssl_certificate /etc/nginx/certs/server.crt;
    ssl_certificate_key /etc/nginx/certs/server.key;

    # ตั้งค่าให้ React ทำงานได้ปกติ
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html;
    }
}